from Package.calculator import calculate, calculator_function
from Package.get_time import get_current_time, get_current_time_function
from Package.get_stock_price import get_stock_price, get_stock_price_function
from Package.tool_call import tool_call_function