from chatbot_functions.calculator import calculate, calculator_function
from chatbot_functions.get_time import get_current_time, get_current_time_function
from chatbot_functions.get_stock_price import get_stock_price, get_stock_price_function
from chatbot_functions.tool_call import tool_call_function